app = "hogwarts"
primary_region = "gru"

[http_service]
  auto_start_machines = true
  auto_stop_machines = false
  force_https = true
  internal_port = 8080
  min_machines_running = 1

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[[vm]]
  size = "performance-1x"
  memory_mb = 2048